[package]
name = "windows-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
cpal = "0.15"
crossbeam-channel = "0.5"
wasapi = "0.22"
